import './globals.css'
import { Inter } from 'next/font/google'
import SearchBar from '../components/SearchBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mi primerita Next app',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <head>
        <title> Mi primerita Next app </title>
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <SearchBar />
        {children}
      </body>
    </html>
  )
}
