import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mi primerita Next app',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <head>
        <title> {`${metadata.title}`} </title>
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <Header />
        {children}
      </body>
    </html>
  )
}
